fix: false
parallel: true
format: progress
ruby_version: 2.6.6
ignore:
  - 'bin/**/*'
  - 'db/schema.rb'
  - 'log/**/*'
  - 'node_modules/**/*'
  - 'public/**/*'
  - 'storage/**/*'
  - 'tmp/**/*'
  - 'vendor/**/*'
  - 'test/**/*':
    - Layout/AlignHash
  - 'app/**/*':
    - Naming/AccessorMethodName
  - 'app/controllers/advertisements_controller.rb':
    - Performance/InefficientHashSearch
