default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_QUEUE_URL", "redis://localhost:6379/1") %>

development:
  <<: *default
  channel_prefix: code_fund_ads_development

test:
  adapter: async

production:
  <<: *default
  channel_prefix: code_fund_ads_production
