common: &defaults
  key: <%= ENV["SCOUT_KEY"] %>
  name: CodeFund
  monitor: <%= ENV.fetch("SCOUT_ENABLED", "false") %>
  ignore:
    - '/okcomputer'
    - '/okcomputer.json'
    - '/okcomputer/all'
    - '/okcomputer/all.json'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
